### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by huijari** [huijari/silver-train#1]
- [x] Nomes de integrantes do grupo
- [x] Explicação do sistema
- [x] Explicação das tecnologias utilizadas
