### ISSUE TITLE
Refatorar as funções mais complexas

### ISSUE THREAD

**Issue by huijari** [huijari/silver-train#3]
As três funções mais complexas devem ser refatoradas de acordo com boas práticas de desenvolvimento (refactoring, clean code, etc). Cada alteração de código deve ser realizada em um commit distinto e com explicações detalhadas.

**Comment by huijari** [comment]
- [x] init@12-51@src/index.ts
- [x] (anonymous)@16-33@src/menu/index.ts
- [x] recreateAccount@7-41@src/menu/changeMasterPassword.ts
